blueprint:
  name: Controller - HomeKit Remote
  description: Map the HomeKit TV Remote to your actual TV Remote
  domain: automation
  input:
    media_player_entity:
      name: Media Player
      description: The media player / TV that HomeKit is controling.
      selector:
        entity:
          domain: media_player
          
variables:
  media_player_entity: !input media_player_entity


mode: queued
max: 10
max_exceeded: warning

trigger:
  - platform: event
    event_type: homekit_tv_remote_key_pressed
    event_data:
      entity_id: !input media_player_entity

action:
  - variables:
      trigger_action: >-
        {{ trigger.event.data.key_name }}

